baseURL = 'https://thriemer.github.io/abandoned-blog'
languageCode = 'en-us'
title = 'Abondoned Blog'
theme = 'abandoned'


[[menus.main]]
name = 'Data Science'
pageRef = '/datascience'
weight = 30


[[menus.main]]
name = 'Trading Bot'
pageRef = '/tradingbot'
weight = 30



[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

